### ISSUE TITLE
Drag & drop for blocks in overview

### ISSUE THREAD

**Issue by vancha** [r-meijerink/DeskGrid-release#1]
Could we get drag & drop support in the overview, with snap-to-grid functionality? That way we could just click an icon, and drag it to wherever we want on the overview, to make the editing process a bit easier.

**Comment by r-meijerink** [comment]
This is implemented now. The release is updated.

**Comment by r-meijerink** [comment]
When you hold left ctrl while dragging & dropping an icon you copy the icon.
